import {parseCsv,toCsv} from './csv.js';
import {GROUPS,reconcile} from './reconcile.js';

const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const displayShift=s=>({day:'День',night:'Ночь'})[s]||s;
const safeCsv=value=>{const text=String(value??'');return /^[\s]*[=+@-]/.test(text)?`'${text}`:text;};
let oee=[],acts=[],report=null,active='all';

function notice(message,error=false){$('message').textContent=message;$('message').classList.toggle('error',error);}
function updateLines(){const selected=$('lineFilter').value;const lines=[...new Set([...oee,...acts].map(r=>r.line).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));$('lineFilter').replaceChildren(new Option('Все линии','all'),...lines.map(x=>new Option(x,x)));$('lineFilter').value=lines.includes(selected)?selected:'all';}
async function loadFile(file,kind){if(!file)return;const rows=parseCsv(await file.text()).map(r=>({...r,source:file.name}));if(kind==='oee'){oee=rows;$('oeeName').textContent=`${file.name} · ${rows.length} строк`;}else{acts=rows;$('actName').textContent=`${file.name} · ${rows.length} строк`;}report=null;$('results').classList.add('hidden');updateLines();notice('Файлы загружены. Выберите параметры и проведите сверку.');}
for(const [input,kind] of [['oeeFile','oee'],['actFile','acts']])$(input).addEventListener('change',async event=>{try{await loadFile(event.target.files[0],kind);}catch(error){notice(error.message,true);}});
$('demoButton').addEventListener('click',async()=>{try{const [o,a]=await Promise.all([fetch('./demo/oee.csv'),fetch('./demo/acts.csv')]);if(!o.ok||!a.ok)throw new Error('Не удалось открыть пример');oee=parseCsv(await o.text()).map(r=>({...r,source:'demo/oee.csv'}));acts=parseCsv(await a.text()).map(r=>({...r,source:'demo/acts.csv'}));$('oeeName').textContent=`Учебный пример · ${oee.length} строк`;$('actName').textContent=`Учебный пример · ${acts.length} строк`;$('fromFilter').value='2026-01-12';$('toFilter').value='2026-01-13';updateLines();run();}catch(error){notice(error.message,true);}});
$('runButton').addEventListener('click',run);
function run(){try{if(!oee.length||!acts.length)throw new Error('Загрузите оба CSV файла или откройте учебный пример.');if($('fromFilter').value&&$('toFilter').value&&$('fromFilter').value>$('toFilter').value)throw new Error('Начальная дата позже конечной.');report=reconcile(oee,acts,{line:$('lineFilter').value,from:$('fromFilter').value,to:$('toFilter').value,tolerance:Number($('tolerance').value)});active='all';$('search').value='';render();$('results').classList.remove('hidden');notice(`Проверено ${report.checked.shifts} смен. Данные обработаны в вашем браузере.`);}catch(error){notice(error.message,true);}}
function render(){const {issues,counts,checked}=report;$('issueCount').textContent=issues.length;$('oeeCount').textContent=checked.oee;$('actCount').textContent=checked.acts;$('shiftCount').textContent=checked.shifts;$('summary').textContent=`${$('lineFilter').selectedOptions[0].textContent} · ${$('fromFilter').value||'начало периода'} — ${$('toFilter').value||'конец периода'}`;
  const buttons=[{id:'all',title:'Все замечания',color:'all'},...GROUPS].map(g=>`<button class="group ${g.color} ${active===g.id?'active':''}" data-group="${g.id}" type="button" aria-pressed="${active===g.id}"><span>${escapeHtml(g.title)}</span><strong>${g.id==='all'?issues.length:counts[g.id]}</strong><small>${g.id==='all'?'Показать полный список':groupSubtitle(g.id)}</small></button>`).join('');$('groups').innerHTML=buttons;for(const b of $('groups').querySelectorAll('button'))b.addEventListener('click',()=>{active=b.dataset.group;render();});renderList();}
function groupSubtitle(id){return {minute_mismatch:'Разница с актами',oee_without_act:'Нет подтверждения',act_without_oee:'Нет записи OEE',category_error:'Колонка или поле акта',balance_outside:'Проверка нормы смены',night_dispute:'Уточнить дату смены'}[id];}
function renderList(){const q=$('search').value.trim().toLocaleLowerCase('ru');const list=report.issues.filter(i=>(active==='all'||i.group===active)&&`${i.title} ${i.why} ${i.line} ${i.date} ${i.shift}`.toLocaleLowerCase('ru').includes(q));$('listTitle').textContent=active==='all'?'Все замечания':GROUPS.find(g=>g.id===active).title;$('listCount').textContent=list.length;$('issueList').innerHTML=list.length?list.map(i=>`<button type="button" class="issue" data-id="${i.id}"><span class="issue-mark ${GROUPS.find(g=>g.id===i.group).color}"></span><span class="issue-main"><b>${escapeHtml(i.title)}</b><small>${escapeHtml(i.why)}</small></span><span class="issue-meta">${escapeHtml(i.line)}<small>${escapeHtml(i.date)} · ${displayShift(i.shift)}</small></span><span class="arrow">→</span></button>`).join(''):'<div class="empty">По выбранным условиям замечаний нет.</div>';for(const b of $('issueList').querySelectorAll('.issue'))b.addEventListener('click',()=>openDetail(report.issues.find(i=>i.id===b.dataset.id)));}
$('search').addEventListener('input',()=>{if(report)renderList();});
function openDetail(issue){$('detailGroup').textContent=GROUPS.find(g=>g.id===issue.group).title;$('detailTitle').textContent=issue.title;const blocks=[['Почему это замечание',issue.why],['Что проверить',issue.action]];const summary=blocks.map(([head,body],j)=>`<section class="explanation ${j?'check':''}"><h3>${head}</h3><p>${escapeHtml(body)}</p></section>`).join('');const sources=[...issue.oee.map(r=>({kind:'OEE',r})),...issue.acts.map(r=>({kind:'АКТ',r}))];$('detailBody').innerHTML=`${summary}<div class="detail-tags"><span>${escapeHtml(issue.line)}</span><span>${escapeHtml(issue.date)}</span><span>${displayShift(issue.shift)}</span></div><h3>Исходные строки</h3>${sources.map(({kind,r})=>`<details class="source-card"><summary><b>${kind}</b><span>${escapeHtml(r.source)} · строка ${r.rowNumber}</span><span class="chevron">⌄</span></summary><div class="source-fields">${Object.entries(r).filter(([k])=>!['source','rowNumber','calculatedMinutes','crossesMidnight','repairMinutes'].includes(k)).map(([k,v])=>`<div><small>${escapeHtml(k)}</small><strong>${escapeHtml(v)}</strong></div>`).join('')}</div></details>`).join('')}`;$('detail').showModal();}
$('closeDetail').addEventListener('click',()=>$('detail').close());$('detail').addEventListener('click',e=>{if(e.target===$('detail'))$('detail').close();});
$('exportButton').addEventListener('click',()=>{if(!report)return;const rows=report.issues.map(i=>({id:i.id,group:GROUPS.find(g=>g.id===i.group).title,line:i.line,date:i.date,shift:displayShift(i.shift),problem:i.title,reason:i.why,action:i.action,oee_rows:i.oee.map(r=>`${r.source}: ${r.rowNumber}`).join('; '),act_rows:i.acts.map(r=>`${r.source}: ${r.rowNumber}`).join('; ')}));const headers=['id','group','line','date','shift','problem','reason','action','oee_rows','act_rows'];const csv=toCsv(rows.map(r=>Object.fromEntries(Object.entries(r).map(([k,v])=>[k,safeCsv(v)]))),headers);const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='oee-remarks-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
